from django.db import models, transaction, IntegrityError
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField

# Extended user class, holds the upload limitations
class ImageUser(models.Model):
	user = models.OneToOneField(User)
	max_file_size = models.IntegerField(default=4096)
	max_total_size = models.IntegerField(default=102400)
	current_total_size = models.IntegerField(default=0)

	def __unicode__(self):
		return self.user.username

class Image(models.Model):

	# Generate hash filenames
	# ------------------------
	# Hash is generated by converting the current datetime in microseconds in to a string,
	# making a md5 hash out of it and taking the first 8 characters of the hash.
	def rename(path):
		def wrapper(instance, filename):
			import hashlib
			from datetime import datetime
	
			ext = filename.split(".")[-1]

			ihash = hashlib.md5(str(datetime.now().microsecond)).hexdigest()[0:8]
			new_filename = ihash + "." + ext
			full_path = path + new_filename

			while Image.objects.filter(img=full_path).count() != 0:
				ihash = hashlib.md5(str(datetime.now().microsecond)).hexdigest()[0:8]
				new_filename = ihash + "." + ext
				full_path = path + new_filename
			
			full_path = path + new_filename

			return full_path
		return wrapper

	datetime = models.DateTimeField(auto_now_add = True)
	img = ImageField(upload_to=rename("imgup/"))
	private = models.BooleanField(default=False)
	title = models.CharField(max_length=30, default="")
	uploader = models.ForeignKey(User)

	def __unicode__(self):
		return self.img